include: package:lints/recommended.yaml

linter:
  rules:
    # Prefer package imports
    always_use_package_imports: true
    prefer_relative_imports: false

analyzer:
  exclude:
    - build/**
    - test/**
